// <auto-generated />
using System;
using MakFood.Wallet.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakFood.Wallet.Infrastructure.Context.Migrations
{
    [DbContext(typeof(MakFoodWalletDbContext))]
    partial class MakFoodWalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.Accounts", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("WalletId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.DiscountCode", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MaximumDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.HasKey("DiscountId");

                    b.ToTable("DiscountCodes", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.OrderDetails", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiscountCodeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("WalletId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.TransactionAggregate.ChargeTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("ChargeTransactions", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.TransactionAggregate.RefundTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("WalletId");

                    b.ToTable("RefundTransactions", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletId");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.Accounts", b =>
                {
                    b.HasOne("MakFood.Wallet.Domain.Model.Entities.Wallet", "Wallet")
                        .WithMany("Accounts")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.OrderDetails", b =>
                {
                    b.HasOne("MakFood.Wallet.Domain.Model.Entities.Wallet", "Wallet")
                        .WithMany("OrderDetails")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.TransactionAggregate.ChargeTransaction", b =>
                {
                    b.HasOne("MakFood.Wallet.Domain.Model.Entities.Wallet", "Wallet")
                        .WithMany("chargeTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.TransactionAggregate.RefundTransaction", b =>
                {
                    b.HasOne("MakFood.Wallet.Domain.Model.Entities.Accounts", "TOAcount")
                        .WithMany("refundTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MakFood.Wallet.Domain.Model.Entities.Wallet", "Wallet")
                        .WithMany("refundTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TOAcount");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.Accounts", b =>
                {
                    b.Navigation("refundTransactions");
                });

            modelBuilder.Entity("MakFood.Wallet.Domain.Model.Entities.Wallet", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("OrderDetails");

                    b.Navigation("chargeTransactions");

                    b.Navigation("refundTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
